export type Label = "scam" | "spam" | "telemarketer" | "safe";

export const EXAMPLES: Array<{ label: Label; text: string }> = [
  { label: "scam", text: "URGENT: Your account has been compromised. Verify your identity here: http://bit.ly/secure-login or it will be suspended within 24 hours." },
  { label: "scam", text: "Dear customer, your PayPal account is limited. Click the link and enter your password to restore access immediately." },
  { label: "scam", text: "I am Prince Adebayo from Nigeria. I need your help transferring $25,000,000 USD. You will receive 30% for your assistance." },
  { label: "scam", text: "Congratulations!!! You have WON a $1,000,000 lottery prize. Send your bank details and a $200 processing fee to claim." },
  { label: "scam", text: "IRS final notice: you owe back taxes. Pay $4,500 in Bitcoin within 24 hours or a warrant will be issued for your arrest." },
  { label: "scam", text: "Your Apple ID has been locked due to suspicious sign-in. Confirm your credit card to unlock: http://apple-verify-id.com" },
  { label: "scam", text: "We detected unusual activity on your Amazon account. Verify your SSN and card number to prevent closure." },
  { label: "scam", text: "Hi grandma, it's me. I'm in jail and need $2000 in gift cards urgently. Please don't tell mom and dad." },
  { label: "scam", text: "Your package could not be delivered. Pay the $1.99 customs fee here to reschedule: http://usps-redelivery.info" },
  { label: "scam", text: "Bitcoin investment opportunity! Guaranteed 500% return in 7 days. Send 0.1 BTC to wallet 1A2b3C4d to get started." },
  { label: "scam", text: "Microsoft security alert: your computer is infected with 5 viruses. Call +1-800-555-0199 immediately for support." },
  { label: "scam", text: "You have an unclaimed inheritance of \u00a34.5 million from a distant relative. Reply with passport and bank info." },
  { label: "scam", text: "Romance: I love you so much darling, but my ship is stuck at customs. Please wire $3,000 so I can come home to you." },
  { label: "scam", text: "Final warning: your Netflix subscription failed. Update billing or account will be terminated: http://netflix-billing.co" },
  { label: "scam", text: "Geek Squad renewal of $499.99 has been charged. To cancel, call this number and provide your bank details." },
  { label: "spam", text: "VIAGRA 80% OFF!!! Cheap meds no prescription needed. Order now and get free shipping worldwide!" },
  { label: "spam", text: "Make $5000 per week working from home. No experience required. Click here to start earning today!" },
  { label: "spam", text: "Hot singles in your area want to meet you tonight. Sign up free and chat now!" },
  { label: "spam", text: "Lose 30 pounds in 30 days with this one weird trick doctors don't want you to know." },
  { label: "spam", text: "Buy cheap Rolex replicas, designer handbags, and sunglasses. Limited time 70% discount!" },
  { label: "spam", text: "Get a free iPhone 15 Pro! Just complete this short survey and pay shipping." },
  { label: "spam", text: "Refinance your mortgage at 1.9% APR. Pre-approved offer expires tonight." },
  { label: "spam", text: "Enlarge your manhood naturally with our herbal supplement. Discreet shipping." },
  { label: "spam", text: "CONGRATULATIONS! You've been selected for a free cruise to the Bahamas. Reply YES to claim." },
  { label: "spam", text: "Work from home moms are earning $8000/month with this simple system. Read more here." },
  { label: "spam", text: "Cheap car insurance quotes in 60 seconds. Save up to 40% on your premium today." },
  { label: "spam", text: "Free trial of weight loss gummies as seen on Shark Tank! Just pay shipping." },
  { label: "spam", text: "Subscribe now and get 90% off on premium VPN service for life. Limited offer!" },
  { label: "spam", text: "Earn a degree in 7 days. No coursework required. Diploma mailed directly to you." },
  { label: "spam", text: "Best CBD oil deals \u2014 buy 2 get 3 free. Doctor approved. Order discreetly online." },
  { label: "telemarketer", text: "Hi, this is Jessica from HomeShield Warranty. We're calling about extending coverage on your vehicle. Press 1 to speak with an agent." },
  { label: "telemarketer", text: "Hello, we're reaching out about solar panel installation for your home. Homeowners in your area qualify for a free quote." },
  { label: "telemarketer", text: "This is a courtesy call regarding your credit card interest rate. You may qualify for a lower APR \u2014 press 1 to learn more." },
  { label: "telemarketer", text: "Hi there, I'm calling from ABC Energy. We can lower your monthly electricity bill by up to 25%. Do you have a minute?" },
  { label: "telemarketer", text: "We're following up on your recent inquiry about Medicare supplemental insurance plans. A licensed agent will assist you." },
  { label: "telemarketer", text: "Hi, I'm calling on behalf of Comfort Windows. We're offering a free in-home estimate for replacement windows this week." },
  { label: "telemarketer", text: "Good afternoon, this is Mark from Premier Vacation Club. You've been selected for a complimentary 3-night Orlando getaway." },
  { label: "telemarketer", text: "Hello, we noticed your auto warranty may be expiring. Would you like to speak with a specialist about extending it?" },
  { label: "telemarketer", text: "Hi, I'm calling about a special promotion on home security systems for your neighborhood. Free installation this month only." },
  { label: "telemarketer", text: "This is Lisa with HealthQuotes. Can I ask a few quick questions to find you affordable health insurance options?" },
  { label: "telemarketer", text: "Hi, calling from Spectrum. We have a new bundle available for internet and TV in your area at a promotional rate." },
  { label: "telemarketer", text: "Good morning, we're a debt relief agency and we can help reduce your credit card balances by up to 50%." },
  { label: "telemarketer", text: "Hi, this is a follow-up on the timeshare survey you completed. Do you have a few minutes to discuss?" },
  { label: "telemarketer", text: "Hello, calling from Roof Pros. We're in your neighborhood next week and offering free roof inspections." },
  { label: "telemarketer", text: "Hi, I'm with a market research firm conducting a brief survey about consumer products. It only takes 5 minutes." },
  { label: "safe", text: "Hey, are we still on for lunch tomorrow at noon? Let me know if you want to reschedule." },
  { label: "safe", text: "Thanks for sending over the report. I've added a few comments in the doc \u2014 let's review on our 1:1 Thursday." },
  { label: "safe", text: "Reminder: your dentist appointment is scheduled for Friday at 3:00 PM. Reply CANCEL if you can't make it." },
  { label: "safe", text: "Your order #A-1042 has shipped and will arrive on Wednesday. Track it in your account." },
  { label: "safe", text: "Mom called, she wants to know if you're coming home for Thanksgiving this year. Give her a ring when you can." },
  { label: "safe", text: "The PR is ready for review. CI is green and I've added unit tests for the new auth flow." },
  { label: "safe", text: "Meeting notes from today's standup are in the shared drive. Action items assigned in the doc." },
  { label: "safe", text: "Happy birthday! Hope you have an amazing day. We should grab drinks this weekend to celebrate." },
  { label: "safe", text: "Your monthly statement is now available. Log in to your online banking to view it." },
  { label: "safe", text: "I attached the slides for next week's presentation. Let me know if you'd like to add anything before Friday." },
  { label: "safe", text: "Thanks for the interview yesterday. We'll be in touch next week with next steps." },
  { label: "safe", text: "The library books you reserved are ready for pickup. They'll be held at the front desk until Monday." },
  { label: "safe", text: "Quick question \u2014 do you have the latest version of the design file? I can't find it in Figma." },
  { label: "safe", text: "Project kickoff is confirmed for Tuesday 10am in conference room B. Calendar invite to follow." },
  { label: "safe", text: "Following up on my last email \u2014 let me know if you had a chance to look at the proposal." },
];
